// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Forward callbacks from external servers to your local environment.\n",
    "title": "callback-teleporter",
    "version": "1.0.0"
  },
  "paths": {
    "/healthcheck": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "success\n"
          },
          "500": {
            "description": "interanal server error"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Forward callbacks from external servers to your local environment.\n",
    "title": "callback-teleporter",
    "version": "1.0.0"
  },
  "paths": {
    "/healthcheck": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "success\n"
          },
          "500": {
            "description": "interanal server error"
          }
        }
      }
    }
  }
}`))
}
